# -*- coding: utf-8 -*-
"""ZAPBAIROV01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjZMiwulKdN-sOA_3Xws0xkeEpuT84Uj
"""

####################################
###   VERSÃO 19052026
####################################
import pandas as pd
import streamlit as st

Path1 = "dados/Cadastro_Maguari.xlsx"

import pandas as pd
import streamlit as st

# Carregar dados do Excel
cadastro_maguari = pd.read_excel(Path1)

# Título do app
st.title("ZAPBAIRRO - Seu Marketplace Hiperlocal")

# Seleção de categoria
categorias = cadastro_maguari["categoria"].unique()
categoria_escolhida = st.selectbox("Selecione a categoria:", categorias)

# Filtrar empresas pela categoria
empresas_filtradas = cadastro_maguari[cadastro_maguari["categoria"] == categoria_escolhida]

# Seleção da empresa
empresa_escolhida = st.selectbox("Selecione a empresa:", empresas_filtradas["empresa"])

# Mostrar informações da empresa
dados_empresa = empresas_filtradas[empresas_filtradas["empresa"] == empresa_escolhida].iloc[0]
st.write(f"**Proprietário:** {dados_empresa['proprietario']}")
st.write(f"**Endereço:** {dados_empresa['endereco']}")
st.write(f"**Telefone:** {dados_empresa['celular']}")
st.write(f"**Horário:** {dados_empresa['horario']}")

# Link direto para WhatsApp com mensagem padrão
numero = str(dados_empresa['celular']).replace(" ", "").replace("-", "").replace("(", "").replace(")", "")
mensagem = "Este cliente está entrando na sua loja através do ZAPBAIRRO, agora é com você"

# Monta o link já com a mensagem
link_whatsapp = f"https://wa.me/{numero}?text={mensagem.replace(' ', '%20')}"

st.markdown(f"[💬 Falar no WhatsApp]({link_whatsapp})", unsafe_allow_html=True)

